services:
  - type: web
    name: tikgram-backend
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 5
